version: '3.8'
services:
  app:
    build: .
    container_name: expensoo
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - ENV MONGO_URL="mongodb://mongo:27017/expenso"
      - ENV JWT_Secret='your_jwt_secret_key'
    image: ahmedzia786/expenso
  mongo:
    image: mongo
    container_name: mongoose
    ports:
      - "27017:27017"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
